development:
  clients:
    default:
      uri: <%= ENV["MONGODB"] %>

production:
  clients:
    default:
      uri: <%= ENV["MONGODB"] %>
      options:
        skip_version_check: true
        safe: true

test:
  clients:
    default:
      uri: <%= ENV["MONGODB"] %>
