development:
  clients:
    default:
      uri: <%= ENV["MONGODB"] %>

production:
  clients:
    default:
      uri: <%= ENV["MONGODB"] %>
      options:
        skip_version_check: true
        safe: true

test:
  clients:
    default:
      database: backend_test
      hosts:
        - localhost:27017
      options:
        read:
          mode: :primary
        max_pool_size: 1
